menu:
  Home: /
  Archives: /archives

widgets: 
# - search
- category
- tag
- twitter

excerpt_link: Read More

twitter:
  username: thiagopnts
  show_replies: false
  tweet_count: 5

facebook: thiagopnts
github: thiagopnts
email: thiagopnts+contact@gmail.com
name: Thiago Pontes
about: "Code, coffee and beer."

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss: